// ws/simbana/u3/WS24-PythonWebService/front-end/src/App.vue
<script setup>
import './assets/style.css'
</script>
 

<template>
  <div>
    <h2>Customers</h2>

    <table border="1">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Type</th>
          <th>Discount</th>
          <th>Total Sale</th>
        </tr>
      </thead>

      <tbody>
        <tr v-for="c in customers" :key="c._id">
          <td>{{ c.id }}</td>
          <td>{{ c.fullName }}</td>
          <td>{{ c.email }}</td>
          <td>{{ c.type }}</td>
          <td>{{ c.discount }}%</td>
          <td>{{ c.totalSale }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      customers: []
    }
  },
  async mounted() {
    const res = await fetch("http://127.0.0.1:8000/customers")
    this.customers = await res.json()
  }
}
</script>

<style>
</style>

// ws/ayuquina/u3/WS24WebService/customer-frontend/src/App.jsx
import { useState, useEffect } from 'react'
import './App.css'

function App() {
  const [customers, setCustomers] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const API_URL = 'https://universidad-1i99.onrender.com/oopdatabase/customers'
  //sadasdasd

  useEffect(() => {
    fetch(API_URL)
      .then(response => {
        if (!response.ok) {
          throw new Error('Error al cargar los datos')
        }
        return response.json()
      })
      .then(data => {
        setCustomers(data)
        setLoading(false)
      })
      .catch(err => {
        setError(err.message)
        setLoading(false)
      })
  }, [])

  if (loading) {
    return <div className="loading">Loading data...</div>
  }

  if (error) {
    return (
      <div className="error">
        <strong>Error:</strong> {error}
        <br />
        <small>Asegúrate de que el servidor Python esté corriendo en http://localhost:8000</small>
      </div>
    )
  }

  return (
    <div className="container">
      <h1>Customer Management System</h1>     
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Full Name</th>
            <th>Email</th>
            <th>Type</th>
            <th>Discount (%)</th>
            <th>Total Sale ($)</th>
          </tr>
        </thead>
        <tbody>
          {customers.map((customer) => (
            <tr key={customer._id?.$oid || customer.id}>
              <td>{customer.id}</td>
              <td>{customer.fullName}</td>
              <td>{customer.email}</td>
              <td>{customer.type}</td>
              <td>{customer.discount}</td>
              <td>${customer.totalSale}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

export default App
